import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CenteredContainer from "@/components/Container";
import { getServerSession } from "next-auth";
import SessionProviderClientComponent from "@/components/SessionProvider/SessionProviderClientComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wolfs PDV",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderClientComponent session={session}>
            {children}
        </SessionProviderClientComponent>
      </body>
    </html>
  );
}
